name: date_chat
description: Um aplicativo de encontros.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2
  splashscreen: ^1.3.5
  flutter_feather_icons: ^1.0.3
  flutter_swiper: ^1.1.6
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - foto01.jpeg
    - foto02.jpeg
    - foto03.jpeg
    - foto04.jpeg
    - foto05.jpeg
    - foto06.jpeg
    - foto07.jpeg
    - foto08.jpeg
    - foto09.jpeg
    - foto10.jpeg
    - foto11.jpeg
    - foto12.jpeg
    - foto13.jpeg
    - profile.jpg